# languages is an array of tuples in the format
# (name, code)

languages = [
	("Autodetect Language", "auto"),
	("Asturian", "ast"),
	("Belarusian", "be"),
	("Breton", "br"),
	("Catalan", "ca"),
	("ValencianCatalan", "ca"),
	("Danish", "da"),
	("German (Austria)", "de-AT"),
	("German", "de"),
	("German (Germany)", "de-DE"),
	("German (Swiss)", "de-CH"),
	("Greek", "el"),
	("English (American)", "en-US"),
	("English (Australian)", "en-AU"),
	("English (GB)", "en-GB"),
	("English (Canadian)", "en-CA"),
	("English", "en"),
	("English (New Zealand)", "en-NZ"),
	("English (South African)", "en-ZA"),
	("Esperanto", "eo"),
	("Spanish", "es"),
	("Persian", "fa"),
	("French", "fr"),
	("Galician", "gl"),
	("Icelandic", "is"),
	("Italian", "it"),
	("Japanese", "ja"),
	("Khmer", "km"),
	("Lithuanian", "lt"),
	("Malayalam", "ml"),
	("Dutch", "nl"),
	("Polish", "pl"),
	("Portuguese (Brazil)", "pt-BR"),
	("Portuguese (Portugal)", "pt-PT"),
	("Portuguese", "pt"),
	("Romanian", "ro"),
	("Russian", "ru"),
	("Slovak", "sk"),
	("Slovenian", "sl"),
	("Swedish", "sv"),
	("Tamil", "ta"),
	("Tagalog", "tl"),
	("Ukrainian", "uk"),
	("Chinese", "zh"),
];

